<?php

namespace AppBundle\Repository;

/**
 * DiseaseSymptomsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiseaseSymptomsRepository extends \Doctrine\ORM\EntityRepository
{
}
