<?php

namespace AppBundle\Repository;

/**
 * PollingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollingRepository extends \Doctrine\ORM\EntityRepository
{
}
