<?php

namespace AppBundle\Repository;

/**
 * UsersapiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersapiRepository extends \Doctrine\ORM\EntityRepository
{
}
